

dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - libeigen3-dev

  

# Build steps
script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - export EIGEN_INCLUDE_DIR=/usr/include/eigen3
  # Run your build commands next
  - git submodule add https://github.com/pybind/pybind11 python/pybind11
  - patch -p1 < python2.7.patch 
  - mkdir build
  - cd build
  - cmake .. && make
  - make test
